service: nestjs-serverless-boilerplate

custom:
  defaultStage: dev
  defaultRegion: ap-northeast-2
  envMap:
    dev: development
    prd: production
  regionMap:
    ap-northeast-2: seoul
  warmup:
    enabled: true

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'
    warmup:
      default:
        enabled: true

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: dev-apigw-api
